### ISSUE TITLE
Remove orphans while deploying

### ISSUE THREAD

**Issue by HomemadeAdvanced** [xavier-hernandez/goaccess-for-nginxproxymanager#127]
Hello,

I have started the container after creating the .yml. NPM is in the other .yml located in the same folder for updating reasons. After deploying with "docker compose -f docker-compose2.yml up -d" it shows up that I have to remove orphans. At this point I can access the Dashboard in the browser and everything is working fine.
But I would like to update the container and I would like to react to the shown message, so I run "docker compose down --remove-orphans" , "docker compose pull" and "docker compose up -d".
After that I cannot reach the Dashboard anymore.

**Comment by HomemadeAdvanced** [comment]
I have not figured it out how to do it more easily but it works like this:

docker compose -f docker-compose.yml down --remove-orphans && docker compose -f docker-compose.yml pull && docker compose -f docker-compose.yml up -d && docker compose -f docker-compose2.yml down --remove-orphans && docker compose -f docker compose2.yml pull && docker compose -f docker compose2.yml up -d

**Comment by HomemadeAdvanced** [comment]
Only the last updated container is online. I have both .yml files in the same directory. What am I doing wrong?

**Comment by xavier-hernandez** [comment]
Some of this is related to docker and not this project. Usually, the remove-orphans alert will show up when you've removed something from your yml file and then brought up your yml/containers back up without that old image. It's letting you know that you have images that are no longer in use. That way you don't run out of server space because of all the images your downloading.

If you want to pull the latest for this docker image for example you would run something like this command "docker pull xavierh/goaccess-for-nginxproxymanager" or "docker pull xavierh/goaccess-for-nginxproxymanager:latest" or run watchtower https://containrrr.dev/watchtower.

Hope that answers your question.

**Comment by HomemadeAdvanced** [comment]
Thanks for responding. I know about the update possibilities but I don't know why only the latest update service is online. They seem to override themselfes. The above commands run through without an error but the first updated isn't reachable. I have to add an `&& docker compose -f docker-compose.yml up -d` and then it is working. I will test it out with watchtower maybe it will work then.
