### ISSUE TITLE
Panels menu becomes inaccessible in vertical monitors

### ISSUE THREAD

**Issue by ephraim-beltran** [xavier-hernandez/goaccess-for-nginxproxymanager#142]
In the mobile layout, the Panels menu function is replaced by the layout menu.
The layout menu button is not visible.

**Comment by xavier-hernandez** [comment]
@ephraim-beltran it appears that my container is working just like theirs.  Looks like all the options are just shown to you and you are unable to modify the layout.  

Please visit their live demo, https://goaccess.io/ . If you see an issue in the live demo then you can report it to their repo, https://github.com/allinurl/goaccess,  otherwise, you can re-open this ticket if you think that this container is behaving differently than their demo.
