### ISSUE TITLE
Add a second NPM log directory

### ISSUE THREAD

**Issue by synexTG** [xavier-hernandez/goaccess-for-nginxproxymanager#179]
Hello,

first of all thank you for this great docker image, it is working perfectly. Due to better security i am now running a second instance of nginx proxy manager for external services (Port 443 external, port 444 on second npm instance).

I want to run goaccess for the internal and external instance of nginx proxy manager, how can i achieve this? The logs are in different locations and i only know that you can mount one directory.

Is there any possibility to add a second log directory?

Thanks you!

**Comment by xavier-hernandez** [comment]
I suggest you just run another instance of the app and point that to the new location. Merging directories would cause a problem because both instances might have the same proxy file name. For example, both could have proxy-host-2_access.log. The app how it currently works would merge both files from both instances.
