### ISSUE TITLE
Information update

### ISSUE THREAD

**Issue by FedorAdo** [xavier-hernandez/goaccess-for-nginxproxymanager#69]
Hello.
Is information only updated by restarting the container?

**Comment by xavier-hernandez** [comment]
@FedorAdo if you mean new proxy files yes. Otherwise, the logs are continuously being read by the goaccess application in the container.

**Comment by FedorAdo** [comment]
> Otherwise, the logs are continuously being read by the goaccess application in the container.

docker-compose:

> version: "3.9"
> 
> volumes:
>   nginx-pxmr_logs:
>     external: true
> 
> services:
>   nginx-pxmr:
>     image: jc21/nginx-proxy-manager:latest
>     container_name: nginx-pxmr
>     restart: always
>     ports:
>       - 80:80 # Public HTTP Port
>       - 443:443 # Public HTTPS Port
>     volumes:
>       - /home/fedor/docker/nginx-pm/data:/data
>       - nginx-pxmr_logs:/data/logs
>       - /home/fedor/docker/nginx-pm/letsencrypt:/etc/letsencrypt
>     environment:
>       DB_SQLITE_FILE: "/data/database.sqlite"
>       DISABLE_IPV6: "true"
>     networks:
>       default:
>         ipv4_address: 172.5.0.254
> 
>   npm-goaccess:
>     container_name: npm-goaccess
>     image: xavierh/goaccess-for-nginxproxymanager:latest
>     restart: always
>     depends_on:
>       - nginx-pxmr
>     volumes:
>       - nginx-pxmr_logs:/opt/log
>     environment:
>       SKIP_ARCHIVED_LOGS: "True" #optional
>       DEBUG: "False" #optional
>       BASIC_AUTH: "True" #optional
>       BASIC_AUTH_USERNAME: ${USER} #optional
>       BASIC_AUTH_PASSWORD: ${PASSWORD} #optional
>       EXCLUDE_IPS: 127.0.0.1 #optional - comma delimited
> 
> 
> networks:
>   default:
>     external:
>       name: application

Docker log:
> ...
> Found (25) proxy logs...
> 
> SKIP ARCHIVED LOGS
> TRUE
> 
> EXCLUDE IPS
> 127.0.0.1
> 
> Setting GeoIP Database
> DEFAULT
> 
> DEBUG
>  OFF
>
> RUN NPM GOACCESS
> Daemonized GoAccess: 30

As a result, after the launch - Last Updated: 2022-07-13 11:05:20 +0700 - and that's it, it doesn't change anymore until you stop and start the container again.

**Comment by FedorAdo** [comment]
![npm-2022-07-14 100344](https://user-images.githubusercontent.com/30267668/178889156-6cd47e88-cfdf-4078-aa93-7943b70c883d.jpg)
The problem was this - websocket.  All earned. Thanks

**Comment by xavier-hernandez** [comment]
oh ok, I didn't know you were proxying the container via npm. Yes, the webpage requires websockets support to update the page continuously.

**Comment by xavier-hernandez** [comment]
I'll add this to the readme file. Can I close this thread?

**Comment by FedorAdo** [comment]
> Can I close this thread?
Of course. Once again - thank you very much.

**Comment by xavier-hernandez** [comment]
@FedorAdo I've updated the README file under Possible Issues with the information. Thanks!

**Comment by kmanwar89** [comment]
Hi @xavier-hernandez  - thank you for making this image! It's solved my issues with GoAccess ( no matter what I'd do, it wouldn't recognize the format!), however I seem to be having an issue with GoAccess not loading the logs in realtime despite websockets support enabled in NPM.  In fact, I enable websockets support with *all* of my proxy hosts as I add them.

I believe my issue is due to using NPM as the proxy in front of the container, combined with a custom docker network.  If I disable the docker network (and expose the ports straight on my host machine), it works in real-time, but if I enable the docker network, the connectivity in GoAccess breaks (it says disconnected and has a grey dot next to the gear icon on the left side of the screen, see screenshot below):

<img width="220" alt="image" src="https://user-images.githubusercontent.com/11323060/213927058-2cc8e550-f1dc-4c70-b118-0c3f4ded6804.png">

In summary: 

Working:
- NPM container on docker custom network
- goaccess-for-nginxproxymanager container with port 7880 exposed directly
- websockets enabled

Not working:
- NPM container on docker custom network
- goaccess-for-nginxproxymanager container on docker custom network, port 7880 exposed only within this network
- websockets enabled

Both containers are on the same docker network and have connectivity between them:

```
❯ docker container inspect goaccess | grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.19.0.4",
❯ docker container inspect npm | grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.19.0.16",
```

Any ideas here?
